# Understanding the basics of tensors.
## What is a tensor?
A tensor is very similar to a numpy array. It is used to represent complex data structures and can be a single or multidimensional array. 
A tensor can be a scalar (0D tensor), a vector (1D tensor), a matrix (2D tensor), 3D tensor and higher: multi-dimensional arrays and so on. 
The dimension of a tensor is called its rank. (2D means 2 dimensions, 3D means 3 dimensions and so on).

In [1]:
# To work with tensors we will need pytorch or tensorflow
# to import pytorch you can use the "import torch" and "import tensorflow" to use tensorflow. 
# In this example we will use pytorch

import torch

In [4]:
# using the "arange" function to create a range of numbers between 0-9 (10 numbers working with zero indexing)
# my_torch is a new variable we will assign the new tensor to

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshaping a tensor is a common operation in deep learning. It is used to change the shape of a tensor.
In the example below, we will create a tensor and reshape it to a 2D tensor.
my_torch.reshape(5,2) creates a 2D tensor with 5 rows and 2 columns.
we can also use my_torch.reshape(5,-1) to create a 2D tensor with 5 rows and the number of columns is automatically calculated.
We can use reshape and view to achieve the same results in this case.

In [7]:
my_torch.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [14]:
my_torch.reshape(5,-1)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [9]:
# Creating a 2D tensor with 2 rows and 5 columns each
myt1=my_torch.view(2,5)

In [12]:
myt1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Slicing a tensor is another common operation in deep learning. It is used to extract a part of a tensor.
In the example below, we will create a tensor and slice it to extract the 5th item on the 2nd row. 
Another way to say this is, extracting a value from the 2nd row and 5th column.

In [13]:
myt1[1,4]

tensor(9)

## Math in PyTorch using tensors.
creating 2 tensors and adding them together is a common operation in deep learning. You can also multiply, subtract, divide, and perform other mathematical operations on tensors.

In [21]:
myt10_20=torch.arange(10,20)

In [22]:
myt20_30=torch.arange(20,30)

When we add 2 tensors, the shape of the 2 tensors must be the same. Tensors adds the first element of the first tensor to the first element of the second tensor and so on.
We can add using the + sign or use the add function.

In [24]:
myt10_20+myt20_30

tensor([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [25]:
torch.add(myt20_30,myt10_20)

tensor([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])