# Understanding the basics of tensors.
## What is a tensor?
A tensor is very similar to a numpy array. It is used to represent complex data structures and can be a single or multidimensional array. 
A tensor can be a scalar (0D tensor), a vector (1D tensor), a matrix (2D tensor), 3D tensor and higher: multi-dimensional arrays and so on. 
The dimension of a tensor is called its rank. 

In [1]:
# To work with tensors we will need pytorch or tensorflow
# to import pytorch you can use the "import torch" and "import tensorflow" to use tensorflow. 
# In this example we will use pytorch
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_torch.reshape(5,-1)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [7]:
my_torch.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
myt1=my_torch.view(2,5)

In [12]:
myt1[:,4:]

tensor([[4],
        [9]])